services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-runner
    restart: unless-stopped
    environment:
      RUNNER_URL: https://github.com/wrenth04/autosrt
      RUNNER_TOKEN: your_runner_registration_token
      RUNNER_NAME: docker-runner-01
      RUNNER_LABELS: docker,linux,x64
      RUNNER_GROUP: Default
      RUNNER_WORKDIR: _work
